//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.HeyAlice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.HeyAlice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open chat history.
        /// </summary>
        public static string plugin_chat_history {
            get {
                return ResourceManager.GetString("plugin_chat_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chat with prompt: {0}.
        /// </summary>
        public static string plugin_chat_with_prompt {
            get {
                return ResourceManager.GetString("plugin_chat_with_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick access to Hey Alice app via deep links.
        /// </summary>
        public static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open Hey Alice.
        /// </summary>
        public static string plugin_failed_to_open {
            get {
                return ResourceManager.GetString("plugin_failed_to_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chat.
        /// </summary>
        public static string plugin_new_chat {
            get {
                return ResourceManager.GetString("plugin_new_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey Alice.
        /// </summary>
        public static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open assistant: {0}.
        /// </summary>
        public static string plugin_open_assistant {
            get {
                return ResourceManager.GetString("plugin_open_assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open skill: {0}.
        /// </summary>
        public static string plugin_open_skill {
            get {
                return ResourceManager.GetString("plugin_open_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New chat with {0}: {1}.
        /// </summary>
        public static string plugin_new_chat_with_assistant {
            get {
                return ResourceManager.GetString("plugin_new_chat_with_assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill activation {0}: {1}.
        /// </summary>
        public static string plugin_skill_activation {
            get {
                return ResourceManager.GetString("plugin_skill_activation", resourceCulture);
            }
        }
    }
}
